### ISSUE TITLE
Exception httplib.BadStatusLine in Connector.py

### ISSUE THREAD

**Issue by daniel0076** [hsucw/TWEleReceipt#2]
If the website did not reture correct response code, the Crawler.py will crash
The try catch in `postForm` in Connector.py is wrong to catch multiple exceptions

Error logs

```
Recieve task : KA13199451 105/07/15 -1 100
INFO:root:[OK]Get Image :wm7dE
INFO:root:KA13199451 and 105/07/15
Traceback (most recent call last):
  File "Crawler.py", line 115, in <module>
    receipt = C.Crawl(_data[0],_data[1],int(_data[2]),int(_data[3]))
  File "Crawler.py", line 75, in Crawl
    success = self.Query()
  File "Crawler.py", line 37, in Query
    self.c.postForm( self.c.postPath )
  File "/home/daniel/project/TWEleReceipt/Connector.py", line 98, in postForm
    self.res = self.conn.getresponse()
  File "/usr/lib64/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib64/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

```

**Comment by daniel0076** [comment]
Bugfix in PR #3
the line `except httplib.ResponseNotReady or httplib.BadStatusLine:` in [Connector.py](https://github.com/hsucw/TWEleReceipt/blob/649e719f2317b57f99933c128c5b96d52ba06a66/Connector.py#L106)
should be
`except (httplib.ResponseNotReady, httplib.BadStatusLine):`

[Python2 Doc Reference](https://docs.python.org/2/tutorial/errors.html#handling-exceptions)
